Fix Template so code does not emit error on anonymous type
Error:

..\AdventOfCode\unknown(1,1): error FS3216: type '<>f__AnonymousType24411399681' not found in assembly '<emitted>'. A possible cause may be a version incompatibility. You may need to explicitly reference the correct version of this assembly to allow all referenced components to use the correct version.